"""v2 business objects relationships transactions

V2 schema (brain/transactional_model.md): commercial documents + lines +
cost items, object links, product suppliers, stock positions, user
profiles; additive columns on V1 tables; plus three data backfills so the
existing database keeps its meaning (see _backfill).

Revision ID: 6860c3147791
Revises: fda755364b7c
Create Date: 2026-09-23 22:08:47.132372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6860c3147791'
down_revision: Union[str, None] = 'fda755364b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_links',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('object_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_links_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_object_links_source', ['source_type', 'source_id'], unique=False)
        batch_op.create_index('ix_object_links_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index('ix_object_links_unique', ['source_type', 'source_id', 'target_type', 'target_id', 'relation'], unique=True)

    op.create_table('users',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('DIRECTOR', 'SALES', 'PROCUREMENT', 'OPERATIONS', 'HR', 'EMPLOYEE', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)

    op.create_table('commercial_documents',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('CUSTOMER_REQUEST', 'CUSTOMER_QUOTE', 'CUSTOMER_ORDER', 'CUSTOMER_DELIVERY', 'CUSTOMER_INVOICE', 'PURCHASE_REQUEST', 'SUPPLIER_QUOTE', 'PURCHASE_ORDER', 'RECEPTION', 'SUPPLIER_INVOICE', name='documentkind'), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('internal_reference', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_terms', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commercial_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commercial_documents_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_commercial_documents_company_number', ['company_id', 'number'], unique=True)
        batch_op.create_index(batch_op.f('ix_commercial_documents_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commercial_documents_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commercial_documents_external_reference'), ['external_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_commercial_documents_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_commercial_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_commercial_documents_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('commercial_document_lines',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('price_basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('lead_time_min_days', sa.Float(), nullable=True),
    sa.Column('lead_time_max_days', sa.Float(), nullable=True),
    sa.Column('lead_time_basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('moq', sa.Float(), nullable=True),
    sa.Column('spq', sa.Float(), nullable=True),
    sa.Column('planned_unit_cost', sa.Float(), nullable=True),
    sa.Column('planned_cost_basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'UNKNOWN', name='valuebasis'), nullable=True),
    sa.Column('planned_cost_source', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['commercial_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commercial_document_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commercial_document_lines_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commercial_document_lines_product_id'), ['product_id'], unique=False)

    op.create_table('product_suppliers',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_reference', sa.String(length=120), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('moq', sa.Float(), nullable=True),
    sa.Column('spq', sa.Float(), nullable=True),
    sa.Column('lead_time_min_days', sa.Float(), nullable=True),
    sa.Column('lead_time_max_days', sa.Float(), nullable=True),
    sa.Column('lead_time_basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('payment_terms', sa.String(length=120), nullable=True),
    sa.Column('country_of_origin', sa.String(length=120), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_suppliers_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_product_suppliers_pair', ['product_id', 'supplier_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_suppliers_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_suppliers_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('stock_positions',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('PHYSICAL', 'SUPPLIER', 'POTENTIAL', name='stockkind'), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('quantity_basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_positions_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_stock_positions_key', ['product_id', 'kind', 'supplier_id', 'location'], unique=True)
        batch_op.create_index(batch_op.f('ix_stock_positions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_positions_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('cost_items',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('TRANSPORT', 'CUSTOMS', 'INSURANCE', 'HANDLING', 'OTHER', name='costkind'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('amount_min', sa.Float(), nullable=False),
    sa.Column('amount_max', sa.Float(), nullable=False),
    sa.Column('basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['commercial_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_id'], ['commercial_document_lines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_items_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_items_document_id'), ['document_id'], unique=False)

    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), server_default='received', nullable=False))
        batch_op.add_column(sa.Column('contact_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('from_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('to_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('thread_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.String(length=40), nullable=True))
        batch_op.alter_column('related_entity_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_communications_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_thread_key'), ['thread_key'], unique=False)
        batch_op.create_foreign_key('fk_communications_contact_id', 'contacts', ['contact_id'], ['id'])

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('related_entity_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               existing_nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('related_entity_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               existing_nullable=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('subject_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_subject_id'), ['subject_id'], unique=False)

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.alter_column('related_entity_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('sale_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sale_price_basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'UNKNOWN', name='valuebasis'), server_default='DECLARED', nullable=False))

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.alter_column('related_entity_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               existing_nullable=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_terms', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.JSON(), server_default='[]', nullable=False))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('related_entity_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_document_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('source_line_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_source_document_id'), ['source_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_source_line_id'), ['source_line_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_source_document_id', 'commercial_documents', ['source_document_id'], ['id'])
        batch_op.create_foreign_key('fk_transactions_source_line_id', 'commercial_document_lines', ['source_line_id'], ['id'])

    # ### end Alembic commands ###
    _backfill()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_source_line_id', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_source_document_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_source_line_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_source_document_id'))
        batch_op.drop_column('quantity')
        batch_op.drop_column('source_line_id')
        batch_op.drop_column('source_document_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('related_entity_type',
               existing_type=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('certifications')
        batch_op.drop_column('payment_terms')

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.alter_column('related_entity_type',
               existing_type=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('sale_price_basis')
        batch_op.drop_column('sale_price')
        batch_op.drop_column('unit')
        batch_op.drop_column('description')
        batch_op.drop_column('category')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('brand')

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.alter_column('related_entity_type',
               existing_type=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_subject_id'))
        batch_op.drop_column('subject_id')
        batch_op.drop_column('subject_type')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('related_entity_type',
               existing_type=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('status')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('related_entity_type',
               existing_type=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_communications_contact_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_communications_thread_key'))
        batch_op.drop_index(batch_op.f('ix_communications_status'))
        batch_op.drop_index(batch_op.f('ix_communications_contact_id'))
        batch_op.alter_column('related_entity_type',
               existing_type=sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', 'CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', name='relatedentitytype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
        batch_op.drop_column('purpose')
        batch_op.drop_column('thread_key')
        batch_op.drop_column('to_address')
        batch_op.drop_column('from_address')
        batch_op.drop_column('contact_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('cost_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_items_document_id'))
        batch_op.drop_index(batch_op.f('ix_cost_items_company_id'))

    op.drop_table('cost_items')
    with op.batch_alter_table('stock_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_positions_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_stock_positions_product_id'))
        batch_op.drop_index('ix_stock_positions_key')
        batch_op.drop_index(batch_op.f('ix_stock_positions_company_id'))

    op.drop_table('stock_positions')
    with op.batch_alter_table('product_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_suppliers_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_product_suppliers_product_id'))
        batch_op.drop_index('ix_product_suppliers_pair')
        batch_op.drop_index(batch_op.f('ix_product_suppliers_company_id'))

    op.drop_table('product_suppliers')
    with op.batch_alter_table('commercial_document_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commercial_document_lines_product_id'))
        batch_op.drop_index(batch_op.f('ix_commercial_document_lines_document_id'))

    op.drop_table('commercial_document_lines')
    with op.batch_alter_table('commercial_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commercial_documents_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_commercial_documents_status'))
        batch_op.drop_index(batch_op.f('ix_commercial_documents_kind'))
        batch_op.drop_index(batch_op.f('ix_commercial_documents_external_reference'))
        batch_op.drop_index(batch_op.f('ix_commercial_documents_customer_id'))
        batch_op.drop_index(batch_op.f('ix_commercial_documents_contact_id'))
        batch_op.drop_index('ix_commercial_documents_company_number')
        batch_op.drop_index(batch_op.f('ix_commercial_documents_company_id'))

    op.drop_table('commercial_documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    op.drop_table('users')
    with op.batch_alter_table('object_links', schema=None) as batch_op:
        batch_op.drop_index('ix_object_links_unique')
        batch_op.drop_index('ix_object_links_target')
        batch_op.drop_index('ix_object_links_source')
        batch_op.drop_index(batch_op.f('ix_object_links_company_id'))

    op.drop_table('object_links')
    # ### end Alembic commands ###


def _backfill() -> None:
    """Data backfills keeping V1 rows meaningful under the V2 model:
    1. outbound Communications were sent, not "received";
    2. every Event Log row gets its derived subject (app.core.events.subjects);
    3. every V1 Product.supplier_id becomes a preferred ProductSupplier row
       (its V1 unit_cost as a DECLARED price), so "suppliers of a product"
       has one source of truth from day one."""

    import json
    import uuid as _uuid

    from app.core.events.subjects import infer_subject

    bind = op.get_bind()
    bind.execute(sa.text("UPDATE communications SET status = 'sent' WHERE direction = 'OUTBOUND'"))

    for row in bind.execute(sa.text("SELECT id, payload FROM events")).fetchall():
        payload = row.payload if isinstance(row.payload, dict) else json.loads(row.payload or "{}")
        subject_type, subject_id = infer_subject(payload)
        if subject_id is not None:
            bind.execute(
                sa.text("UPDATE events SET subject_type = :t, subject_id = :i WHERE id = :id"),
                {"t": subject_type, "i": subject_id.hex, "id": row.id},
            )

    rows = bind.execute(
        sa.text("SELECT id, company_id, supplier_id, unit_cost, created_at FROM products WHERE supplier_id IS NOT NULL")
    ).fetchall()
    for row in rows:
        bind.execute(
            sa.text(
                "INSERT INTO product_suppliers (id, company_id, product_id, supplier_id, unit_price, currency, "
                "price_basis, lead_time_basis, certifications, is_preferred, source, created_at, updated_at) "
                "VALUES (:id, :company_id, :product_id, :supplier_id, :unit_price, 'EUR', 'DECLARED', 'UNKNOWN', "
                "'[]', 1, 'v1_migration', :created_at, :created_at)"
            ),
            {
                "id": _uuid.uuid4().hex,
                "company_id": row.company_id,
                "product_id": row.id,
                "supplier_id": row.supplier_id,
                "unit_price": row.unit_cost,
                "created_at": row.created_at,
            },
        )
