"""v2.1 people finance compliance sourcing website

Revision ID: bd13801daf66
Revises: 6860c3147791
Create Date: 2026-09-24 01:20:37.563092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd13801daf66'
down_revision: Union[str, None] = '6860c3147791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_runs',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_runs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_runs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_runs_subject_id'), ['subject_id'], unique=False)

    op.create_table('bank_accounts',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('bank_name', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('masked_identifier', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('balance_basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'SIMULATED', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('balance_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('maturity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_company_id'), ['company_id'], unique=False)

    op.create_table('skill_needs',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('skill', sa.String(length=120), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'SIMULATED', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_needs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_needs_company_id'), ['company_id'], unique=False)

    op.create_table('employees',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weekly_hours', sa.Float(), nullable=True),
    sa.Column('leave_days_remaining', sa.Float(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('data_basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'SIMULATED', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_user_id'), ['user_id'], unique=False)

    op.create_table('candidates',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('communication_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('applied_for', sa.String(length=160), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'SIMULATED', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('extracted_by', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_communication_id'), ['communication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_company_id'), ['company_id'], unique=False)

    op.create_table('cash_movements',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('counterparty', sa.String(length=160), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['commercial_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_movements_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_movements_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_movements_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('employee_cost_items',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('annual_min', sa.Float(), nullable=False),
    sa.Column('annual_max', sa.Float(), nullable=False),
    sa.Column('basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'SIMULATED', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_cost_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_cost_items_employee_id'), ['employee_id'], unique=False)

    op.create_table('shareholders',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('share_class', sa.String(length=30), nullable=False),
    sa.Column('economic_rights_pct', sa.Float(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'SIMULATED', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shareholders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shareholders_company_id'), ['company_id'], unique=False)

    op.create_table('sourcing_leads',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_request_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('found_price', sa.Float(), nullable=True),
    sa.Column('price_basis', sa.Enum('OBSERVED', 'DECLARED', 'ESTIMATED', 'BENCHMARK', 'SIMULATED', 'UNKNOWN', name='valuebasis'), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['commercial_documents.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sourcing_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sourcing_leads_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sourcing_leads_purchase_request_id'), ['purchase_request_id'], unique=False)

    op.create_table('website_change_proposals',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('page_url', sa.String(length=1000), nullable=False),
    sa.Column('field', sa.String(length=30), nullable=False),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ai_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('website_change_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_change_proposals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_change_proposals_run_id'), ['run_id'], unique=False)

    with op.batch_alter_table('business_contexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finance_settings', sa.JSON(), server_default='{}', nullable=False))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_kind', sa.String(length=30), server_default='goods', nullable=False))
        batch_op.add_column(sa.Column('fee_rate_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fee_rate_max', sa.Float(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_employee_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('action_payload', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_assignee_employee_id'), ['assignee_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_foreign_key('fk_tasks_assignee_employee_id', 'employees', ['assignee_employee_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_grants', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('access_revokes', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('access_revokes')
        batch_op.drop_column('access_grants')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_assignee_employee_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_due_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_category'))
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_employee_id'))
        batch_op.drop_column('action_payload')
        batch_op.drop_column('category')
        batch_op.drop_column('due_at')
        batch_op.drop_column('assignee_employee_id')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('fee_rate_max')
        batch_op.drop_column('fee_rate_min')
        batch_op.drop_column('supplier_kind')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('website_url')

    with op.batch_alter_table('business_contexts', schema=None) as batch_op:
        batch_op.drop_column('finance_settings')

    with op.batch_alter_table('website_change_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_change_proposals_run_id'))
        batch_op.drop_index(batch_op.f('ix_website_change_proposals_company_id'))

    op.drop_table('website_change_proposals')
    with op.batch_alter_table('sourcing_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sourcing_leads_purchase_request_id'))
        batch_op.drop_index(batch_op.f('ix_sourcing_leads_company_id'))

    op.drop_table('sourcing_leads')
    with op.batch_alter_table('shareholders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shareholders_company_id'))

    op.drop_table('shareholders')
    with op.batch_alter_table('employee_cost_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_cost_items_employee_id'))

    op.drop_table('employee_cost_items')
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_movements_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_cash_movements_company_id'))
        batch_op.drop_index(batch_op.f('ix_cash_movements_account_id'))

    op.drop_table('cash_movements')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_company_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_communication_id'))

    op.drop_table('candidates')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_user_id'))
        batch_op.drop_index(batch_op.f('ix_employees_company_id'))

    op.drop_table('employees')
    with op.batch_alter_table('skill_needs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_needs_company_id'))

    op.drop_table('skill_needs')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_company_id'))

    op.drop_table('bank_accounts')
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_runs_subject_id'))
        batch_op.drop_index(batch_op.f('ix_ai_runs_kind'))
        batch_op.drop_index(batch_op.f('ix_ai_runs_company_id'))

    op.drop_table('ai_runs')
    # ### end Alembic commands ###
