"""v2.2 payments installments credit notes delivery tracking

Additive: two tables (payment_installments, credit_applications), nullable
columns (cash_movements.customer_id/supplier_id, document carrier/tracking,
line non-conformity) and two new document kinds (the `kind` column widens;
on PostgreSQL the enum types also receive the values they were missing).

Revision ID: d1688efa5611
Revises: bd13801daf66
Create Date: 2026-09-25 19:52:15.967751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1688efa5611'
down_revision: Union[str, None] = 'bd13801daf66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_DOCUMENT_KINDS = ('CUSTOMER_CREDIT_NOTE', 'SUPPLIER_CREDIT_NOTE')

# PostgreSQL only: enum values added to the models over time whose earlier
# migrations only widened a SQLite VARCHAR -- on PostgreSQL the native enum
# types never received them (found when validating a PostgreSQL deployment).
# Brought in line here so a PostgreSQL database at head accepts every value
# the application writes. No effect on SQLite (no native enum types).
PG_MISSING_ENUM_VALUES = {
    'documentkind': NEW_DOCUMENT_KINDS,
    'taskstatus': ('REJECTED', 'EXECUTED'),
    'relatedentitytype': ('CONTACT', 'COMMUNICATION', 'COMMERCIAL_DOCUMENT', 'EMPLOYEE', 'CANDIDATE'),
    'valuebasis': ('SIMULATED',),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_applications',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('credit_note_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('applied_amount', sa.Float(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['credit_note_id'], ['commercial_documents.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['commercial_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_applications_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_applications_credit_note_id'), ['credit_note_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_credit_applications_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('payment_installments',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['commercial_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_installments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_installments_document_id'), ['document_id'], unique=False)

    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cash_movements_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_movements_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_foreign_key('fk_cash_movements_supplier_id', 'suppliers', ['supplier_id'], ['id'])
        batch_op.create_foreign_key('fk_cash_movements_customer_id', 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('commercial_document_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_nonconforming', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nonconformity_note', sa.String(length=255), nullable=True))

    with op.batch_alter_table('commercial_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrier', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=120), nullable=True))

    # The two new document kinds (+ the values listed in PG_MISSING_ENUM_VALUES).
    # On PostgreSQL the enum values must be added to the native types (an
    # alter_column would keep the old type without them). On SQLite `kind` is
    # a VARCHAR that only needs to widen.
    if op.get_bind().dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            for enum_type, values in PG_MISSING_ENUM_VALUES.items():
                for value in values:
                    op.execute(f"ALTER TYPE {enum_type} ADD VALUE IF NOT EXISTS '{value}'")
    else:
        with op.batch_alter_table('commercial_documents', schema=None) as batch_op:
            batch_op.alter_column('kind',
                   existing_type=sa.VARCHAR(length=17),
                   type_=sa.Enum('CUSTOMER_REQUEST', 'CUSTOMER_QUOTE', 'CUSTOMER_ORDER', 'CUSTOMER_DELIVERY', 'CUSTOMER_INVOICE', 'PURCHASE_REQUEST', 'SUPPLIER_QUOTE', 'PURCHASE_ORDER', 'RECEPTION', 'SUPPLIER_INVOICE', 'CUSTOMER_CREDIT_NOTE', 'SUPPLIER_CREDIT_NOTE', name='documentkind'),
                   existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL cannot drop values from an enum type: the two kinds stay
    # declared (unused) after a downgrade. SQLite narrows the column back.
    if op.get_bind().dialect.name != "postgresql":
        with op.batch_alter_table('commercial_documents', schema=None) as batch_op:
            batch_op.alter_column('kind',
                   existing_type=sa.Enum('CUSTOMER_REQUEST', 'CUSTOMER_QUOTE', 'CUSTOMER_ORDER', 'CUSTOMER_DELIVERY', 'CUSTOMER_INVOICE', 'PURCHASE_REQUEST', 'SUPPLIER_QUOTE', 'PURCHASE_ORDER', 'RECEPTION', 'SUPPLIER_INVOICE', 'CUSTOMER_CREDIT_NOTE', 'SUPPLIER_CREDIT_NOTE', name='documentkind'),
                   type_=sa.VARCHAR(length=17),
                   existing_nullable=False)
    with op.batch_alter_table('commercial_documents', schema=None) as batch_op:
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('carrier')

    with op.batch_alter_table('commercial_document_lines', schema=None) as batch_op:
        batch_op.drop_column('nonconformity_note')
        batch_op.drop_column('quantity_nonconforming')

    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cash_movements_customer_id', type_='foreignkey')
        batch_op.drop_constraint('fk_cash_movements_supplier_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cash_movements_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_cash_movements_customer_id'))
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('payment_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_installments_document_id'))
        batch_op.drop_index(batch_op.f('ix_payment_installments_company_id'))

    op.drop_table('payment_installments')
    with op.batch_alter_table('credit_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_applications_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_credit_applications_credit_note_id'))
        batch_op.drop_index(batch_op.f('ix_credit_applications_company_id'))

    op.drop_table('credit_applications')
    # ### end Alembic commands ###
