"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Locale = "fr" | "en";

// Centralized interface labels (Step 28 §7) -- one dictionary, never
// per-component duplicate translations. Scope: the app's chrome and static
// page text only. Content generated by the backend (decisions, risks,
// narrative, demo data) stays in French: translating server-generated
// content would need backend i18n, which is out of scope for this pass --
// the switch never pretends to translate what it doesn't.
const DICT = {
  "nav.home": { fr: "Accueil", en: "Home" },
  "nav.command_center": { fr: "Centre de contrôle", en: "Command Center" },
  "nav.company_group": { fr: "Entreprise", en: "Business" },
  "nav.finance": { fr: "Finance", en: "Finance" },
  "nav.procurement": { fr: "Achats", en: "Procurement" },
  "nav.sales": { fr: "Ventes", en: "Sales" },
  "nav.data_group": { fr: "Données", en: "Data" },
  "nav.data_entities": { fr: "Fournisseurs, clients, produits", en: "Suppliers, customers, products" },
  "nav.contacts": { fr: "Contacts", en: "Contacts" },
  "nav.intelligence_group": { fr: "Intelligence", en: "Intelligence" },
  "nav.decision_intelligence": { fr: "Décisionnelle", en: "Decision Intelligence" },
  "nav.risks": { fr: "Risques", en: "Risks" },
  "nav.opportunities": { fr: "Opportunités", en: "Opportunities" },
  "nav.actions_group": { fr: "Actions", en: "Actions" },
  "nav.tasks": { fr: "Tâches", en: "Tasks" },
  "nav.activity": { fr: "Activité de l'entreprise", en: "Company activity" },
  "nav.ai_group": { fr: "IA", en: "AI" },
  "nav.ask_ai": { fr: "Demander à l'IA", en: "Ask AI" },
  "nav.configure_company": { fr: "Configurer l'entreprise", en: "Configure company" },
  "nav.configuration": { fr: "Configuration", en: "Settings" },
  "nav.live": { fr: "Data Core · en direct", en: "Data Core · live" },
  "topbar.open_menu": { fr: "Ouvrir le menu", en: "Open menu" },
  "topbar.pending": { fr: "action(s) en attente de validation", en: "action(s) pending validation" },
  // V2 navigation (brain/navigation_v2.md)
  "nav.operations_group": { fr: "Opérations", en: "Operations" },
  "nav.steering_group": { fr: "Pilotage", en: "Steering" },
  "nav.catalog": { fr: "Catalogue & stock", en: "Catalog & stock" },
  "nav.communications": { fr: "Communications", en: "Communications" },
  "nav.intelligence": { fr: "Intelligence", en: "Intelligence" },
  "nav.actions": { fr: "Actions & validations", en: "Actions & approvals" },
  "nav.documents": { fr: "Document", en: "Document" },
  "topbar.profile": { fr: "Profil", en: "Profile" },
  // V2.1
  "nav.people": { fr: "Équipe", en: "Team" },
  "nav.direction": { fr: "Direction", en: "Leadership" },
  "topbar.no_profile": { fr: "Aucun profil (accès complet)", en: "No profile (full access)" },
} as const;

export type LabelKey = keyof typeof DICT;

interface LocaleContextValue {
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: (key: LabelKey) => string;
}

const LocaleContext = createContext<LocaleContextValue | null>(null);

const STORAGE_KEY = "ai-business-os-locale";

export function LocaleProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("fr");

  useEffect(() => {
    try {
      const stored = window.localStorage.getItem(STORAGE_KEY);
      // eslint-disable-next-line react-hooks/set-state-in-effect -- synchronizing with an external system (localStorage), the canonical use case for an effect.
      if (stored === "fr" || stored === "en") setLocaleState(stored);
    } catch {
      // localStorage unavailable (private browsing, etc.) -- French default stands.
    }
  }, []);

  function setLocale(l: Locale) {
    setLocaleState(l);
    try {
      window.localStorage.setItem(STORAGE_KEY, l);
    } catch {
      // Soft failure: the toggle still works for the current page view.
    }
  }

  function t(key: LabelKey): string {
    return DICT[key][locale];
  }

  return <LocaleContext.Provider value={{ locale, setLocale, t }}>{children}</LocaleContext.Provider>;
}

export function useLocale(): LocaleContextValue {
  const ctx = useContext(LocaleContext);
  if (!ctx) throw new Error("useLocale must be used within a LocaleProvider");
  return ctx;
}
